Migrate to Yarn 3
wix-incubator/autoviews pull request #42
Opened 2022-03-24 17:36 UTC by denysdovhan

## Summary

* Migrate to Yarn 3
* Drop Lerna in favor of workspace tools

@Fer0x could you verify node binaries will be linked properly. You said there should be some option set in configs in order to do that?

## How did you test this change?

Just use Yarn 🤷🏻

2022-03-24 18:07 UTC, denysdovhan commented
@Fer0x seems like the problem with resolving dev deps in child packages is present here. That's why CI is failing at the moment.

2022-03-24 18:36 UTC, Fer0x requested changes

2022-03-24 18:36 UTC, Fer0x commented on package.json
> +    "test": "is-ci && jest --maxWorkers=7 || jest --maxWorkers=50%"
`--maxWorkers=7` is requirement for internal Wix CI. Also, don't know if  any `--maxWorkers` affects jest performance on GitHub Actions

2022-03-24 18:36 UTC, Fer0x commented on .gitignore
> +.pnp.js
better use ignores from this guide https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

2022-04-01 14:17 UTC, denysdovhan commented
Closing this, because yarn 3 is not ready to be implemented.

2022-04-01 14:17 UTC, closed without merging